name: dataEx
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.11
  - conda=4.14.0
  - pandoc=2.16.2
  - folium=0.12.1.post1
  - jpype1=1.3.0
  - jupyter-dash=0.4.0
  - jupyterlab=3.3.2
  - matplotlib=3.5.1
  - numpy=1.22.3
  - pandas=1.4.2
  - plotly=5.4.0
  - pyreadstat=1.1.4
  - scikit-learn=1.0.2
  - seaborn=0.11.2
  - wordcloud=1.8.1
  - pip:
      - konlpy==0.6.0
      - pydataset==0.2.0